Checkerboard removal
beala/deep-image-prior-tensorflow pull request #1
Opened 2018-03-12 16:32 UTC by holongate

hi!
This is a quick (and easy) fix for removing your checkerboard artifact.
- Corrected kernel = 1 in second block of up_layer
- Added a final conv2D + sigmoid of (1x1x3) to restore initial image shape (this was the missing bit that created the checkerboard artifact)

(Also, upgraded to Python 3.6 and tensorflow 1.5.)

Keep the good work going on!
Have fun.

2018-03-19 18:41 UTC, beala requested changes
Nice work! Thanks for making this PR.

I left a couple comments. Also, feel free to make a contributors file and add your name.

2018-03-19 18:41 UTC, beala commented on README.md
> +- Install python ~~2.6~~ 3.6, [tensorflow](https://www.tensorflow.org/install/) (tested on ~~1.4.0~~ 1.5.0+), numpy, and scipy.
No need for strikethroughs here (and below).

2018-03-19 18:41 UTC, beala commented on deepimg.py
> +#E = tf.reduce_mean(tf.squared_difference(gblur(out), image))
Can delete this rather than commenting out.

2018-03-23 17:35 UTC, holongate commented
Done!

2018-03-23 22:31 UTC, merged